"""change type int to float

Revision ID: a086187c6377
Revises: f0c129bdf9b3
Create Date: 2025-12-22 15:53:53.016197

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a086187c6377"
down_revision: Union[str, Sequence[str], None] = "f0c129bdf9b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sensor_2",
        "frequency_torque_1",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_comment="Момент ПЧ 1",
        existing_nullable=False,
    )
    op.alter_column(
        "sensor_2",
        "frequency_torque_2",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_comment="Момент ПЧ 2",
        existing_nullable=False,
    )
    op.alter_column(
        "sensor_2",
        "frequency_torque_3",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_comment="Момент ПЧ 3",
        existing_nullable=False,
    )
    op.alter_column(
        "sensor_2",
        "frequency_torque_4",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_comment="Момент ПЧ 4",
        existing_nullable=False,
    )
    op.alter_column(
        "sensor_2",
        "converter_frequency_1",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_comment="Частота ПЧ 1",
        existing_nullable=False,
    )
    op.alter_column(
        "sensor_2",
        "converter_frequency_2",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_comment="Частота ПЧ 2",
        existing_nullable=False,
    )
    op.alter_column(
        "sensor_2",
        "converter_frequency_3",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_comment="Частота ПЧ 3",
        existing_nullable=False,
    )
    op.alter_column(
        "sensor_2",
        "converter_frequency_4",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_comment="Частота ПЧ 4",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sensor_2",
        "converter_frequency_4",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_comment="Частота ПЧ 4",
        existing_nullable=False,
    )
    op.alter_column(
        "sensor_2",
        "converter_frequency_3",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_comment="Частота ПЧ 3",
        existing_nullable=False,
    )
    op.alter_column(
        "sensor_2",
        "converter_frequency_2",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_comment="Частота ПЧ 2",
        existing_nullable=False,
    )
    op.alter_column(
        "sensor_2",
        "converter_frequency_1",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_comment="Частота ПЧ 1",
        existing_nullable=False,
    )
    op.alter_column(
        "sensor_2",
        "frequency_torque_4",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_comment="Момент ПЧ 4",
        existing_nullable=False,
    )
    op.alter_column(
        "sensor_2",
        "frequency_torque_3",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_comment="Момент ПЧ 3",
        existing_nullable=False,
    )
    op.alter_column(
        "sensor_2",
        "frequency_torque_2",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_comment="Момент ПЧ 2",
        existing_nullable=False,
    )
    op.alter_column(
        "sensor_2",
        "frequency_torque_1",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_comment="Момент ПЧ 1",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
