"""fix tables

Revision ID: 9222582fcca6
Revises: 2f184700fc80
Create Date: 2025-12-01 19:05:50.327508

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9222582fcca6"
down_revision: Union[str, Sequence[str], None] = "2f184700fc80"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "screw",
        sa.Column(
            "screw_id", sa.BigInteger(), autoincrement=True, nullable=False
        ),
        sa.Column(
            "serial_id",
            sa.Integer(),
            nullable=False,
            comment="Порядковый номер гайки в рельсе",
        ),
        sa.Column(
            "status",
            sa.Enum(
                "IN_PROGRESS",
                "COMPLETED",
                "COMPLETED_WITH_ERROR",
                name="screw_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "rail_id",
            sa.BigInteger(),
            nullable=False,
            comment="идентификатор рельса",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["rail_id"],
            ["rail.rail_id"],
        ),
        sa.PrimaryKeyConstraint("screw_id"),
    )
    op.drop_column("rail", "errors_count")
    op.add_column(
        "sensor_2",
        sa.Column(
            "screw_id",
            sa.BigInteger(),
            nullable=False,
            comment="идентификатор гайки",
        ),
    )
    op.add_column(
        "sensor_2",
        sa.Column(
            "resistance", sa.Float(), nullable=False, comment="Сопротивление"
        ),
    )
    op.add_column(
        "sensor_2",
        sa.Column(
            "temperature", sa.Float(), nullable=False, comment="Температура"
        ),
    )
    op.add_column(
        "sensor_2",
        sa.Column(
            "humidity", sa.Float(), nullable=False, comment="Влажность %"
        ),
    )
    op.add_column(
        "sensor_2",
        sa.Column(
            "frequency_status_1",
            sa.Integer(),
            nullable=False,
            comment="Состояние ПЧ 1",
        ),
    )
    op.add_column(
        "sensor_2",
        sa.Column(
            "frequency_status_2",
            sa.Integer(),
            nullable=False,
            comment="Состояние ПЧ 2",
        ),
    )
    op.add_column(
        "sensor_2",
        sa.Column(
            "frequency_status_3",
            sa.Integer(),
            nullable=False,
            comment="Состояние ПЧ 3",
        ),
    )
    op.add_column(
        "sensor_2",
        sa.Column(
            "frequency_status_4",
            sa.Integer(),
            nullable=False,
            comment="Состояние ПЧ 4",
        ),
    )
    op.add_column(
        "sensor_2",
        sa.Column(
            "frequency_torque_1",
            sa.Integer(),
            nullable=False,
            comment="Момент ПЧ 1",
        ),
    )
    op.add_column(
        "sensor_2",
        sa.Column(
            "frequency_torque_2",
            sa.Integer(),
            nullable=False,
            comment="Момент ПЧ 2",
        ),
    )
    op.add_column(
        "sensor_2",
        sa.Column(
            "frequency_torque_3",
            sa.Integer(),
            nullable=False,
            comment="Момент ПЧ 3",
        ),
    )
    op.add_column(
        "sensor_2",
        sa.Column(
            "frequency_torque_4",
            sa.Integer(),
            nullable=False,
            comment="Момент ПЧ 4",
        ),
    )
    op.add_column(
        "sensor_2",
        sa.Column(
            "converter_frequency_1",
            sa.Integer(),
            nullable=False,
            comment="Частота ПЧ 1",
        ),
    )
    op.add_column(
        "sensor_2",
        sa.Column(
            "converter_frequency_2",
            sa.Integer(),
            nullable=False,
            comment="Частота ПЧ 2",
        ),
    )
    op.add_column(
        "sensor_2",
        sa.Column(
            "converter_frequency_3",
            sa.Integer(),
            nullable=False,
            comment="Частота ПЧ 3",
        ),
    )
    op.add_column(
        "sensor_2",
        sa.Column(
            "converter_frequency_4",
            sa.Integer(),
            nullable=False,
            comment="Частота ПЧ 4",
        ),
    )
    op.drop_constraint(
        op.f("sensor_2_rail_id_fkey"), "sensor_2", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "sensor_2", "screw", ["screw_id"], ["screw_id"]
    )
    op.drop_column("sensor_2", "phase_amperage")
    op.drop_column("sensor_2", "revolutions_PC_alt")
    op.drop_column("sensor_2", "turnover")
    op.drop_column("sensor_2", "amperage")
    op.drop_column("sensor_2", "resistance_1")
    op.drop_column("sensor_2", "moment_amperage_percent")
    op.drop_column("sensor_2", "moment_percent")
    op.drop_column("sensor_2", "resistance_2")
    op.drop_column("sensor_2", "moment_PC")
    op.drop_column("sensor_2", "status_PC")
    op.drop_column("sensor_2", "rail_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sensor_2",
        sa.Column("rail_id", sa.BIGINT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "sensor_2",
        sa.Column(
            "status_PC",
            sa.BIGINT(),
            autoincrement=False,
            nullable=False,
            comment="Статус ПЧ",
        ),
    )
    op.add_column(
        "sensor_2",
        sa.Column(
            "moment_PC",
            sa.BIGINT(),
            autoincrement=False,
            nullable=False,
            comment="Момент ПЧ",
        ),
    )
    op.add_column(
        "sensor_2",
        sa.Column(
            "resistance_2",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
            comment="Сопротивление 2 (<=4)",
        ),
    )
    op.add_column(
        "sensor_2",
        sa.Column(
            "moment_percent",
            sa.BIGINT(),
            autoincrement=False,
            nullable=False,
            comment="Момент %",
        ),
    )
    op.add_column(
        "sensor_2",
        sa.Column(
            "moment_amperage_percent",
            sa.BIGINT(),
            autoincrement=False,
            nullable=False,
            comment="Момент (т) %",
        ),
    )
    op.add_column(
        "sensor_2",
        sa.Column(
            "resistance_1",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
            comment="Сопротивление 1",
        ),
    )
    op.add_column(
        "sensor_2",
        sa.Column(
            "amperage",
            sa.BIGINT(),
            autoincrement=False,
            nullable=False,
            comment="Ток ПЧ",
        ),
    )
    op.add_column(
        "sensor_2",
        sa.Column(
            "turnover",
            sa.BIGINT(),
            autoincrement=False,
            nullable=False,
            comment="Обороты ПЧ",
        ),
    )
    op.add_column(
        "sensor_2",
        sa.Column(
            "revolutions_PC_alt",
            sa.BIGINT(),
            autoincrement=False,
            nullable=False,
            comment="Обороты ПЧ alt",
        ),
    )
    op.add_column(
        "sensor_2",
        sa.Column(
            "phase_amperage",
            sa.BIGINT(),
            autoincrement=False,
            nullable=False,
            comment="Фазный ток",
        ),
    )
    op.drop_constraint(None, "sensor_2", type_="foreignkey")
    op.create_foreign_key(
        op.f("sensor_2_rail_id_fkey"),
        "sensor_2",
        "rail",
        ["rail_id"],
        ["rail_id"],
    )
    op.drop_column("sensor_2", "converter_frequency_4")
    op.drop_column("sensor_2", "converter_frequency_3")
    op.drop_column("sensor_2", "converter_frequency_2")
    op.drop_column("sensor_2", "converter_frequency_1")
    op.drop_column("sensor_2", "frequency_torque_4")
    op.drop_column("sensor_2", "frequency_torque_3")
    op.drop_column("sensor_2", "frequency_torque_2")
    op.drop_column("sensor_2", "frequency_torque_1")
    op.drop_column("sensor_2", "frequency_status_4")
    op.drop_column("sensor_2", "frequency_status_3")
    op.drop_column("sensor_2", "frequency_status_2")
    op.drop_column("sensor_2", "frequency_status_1")
    op.drop_column("sensor_2", "humidity")
    op.drop_column("sensor_2", "temperature")
    op.drop_column("sensor_2", "resistance")
    op.drop_column("sensor_2", "screw_id")
    op.add_column(
        "rail",
        sa.Column(
            "errors_count", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_table("screw")
    # ### end Alembic commands ###
