"""add treshhold

Revision ID: 2f184700fc80
Revises: 836aca8686d2
Create Date: 2025-11-30 00:50:51.401298

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2f184700fc80"
down_revision: Union[str, Sequence[str], None] = "836aca8686d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "threshold",
        sa.Column(
            "threshold_id", sa.BigInteger(), autoincrement=True, nullable=False
        ),
        sa.Column("value", sa.String(length=255), nullable=False),
        sa.Column("min_value", sa.Float(), nullable=False),
        sa.Column("max_value", sa.Float(), nullable=False),
        sa.Column("is_critical", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("threshold_id"),
    )
    op.add_column(
        "rail", sa.Column("errors_count", sa.Integer(), nullable=False)
    )
    op.alter_column(
        "rail",
        "status",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Enum(
            "IN_PROGRESS",
            "COMPLETED",
            "FAILED",
            name="rail_status",
            native_enum=False,
        ),
        existing_nullable=False,
    )
    op.add_column(
        "sensor_2", sa.Column("rail_id", sa.BigInteger(), nullable=True)
    )
    op.create_foreign_key(None, "sensor_2", "rail", ["rail_id"], ["rail_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sensor_2", type_="foreignkey")
    op.drop_column("sensor_2", "rail_id")
    op.alter_column(
        "rail",
        "status",
        existing_type=sa.Enum(
            "IN_PROGRESS",
            "COMPLETED",
            "FAILED",
            name="rail_status",
            native_enum=False,
        ),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.drop_column("rail", "errors_count")
    op.drop_table("threshold")
    # ### end Alembic commands ###
