"""fix tables

Revision ID: b1370a9f7a34
Revises: 9222582fcca6
Create Date: 2025-12-06 15:25:49.024923

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b1370a9f7a34"
down_revision: Union[str, Sequence[str], None] = "9222582fcca6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "rail",
        "sleepers",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Integer(),
        postgresql_using="sleepers::integer",
        existing_nullable=True,
    )
    op.drop_constraint(op.f("screw_rail_id_fkey"), "screw", type_="foreignkey")
    op.create_foreign_key(
        None,
        "screw",
        "rail",
        ["rail_id"],
        ["rail_id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("sensor_1_rail_id_fkey"), "sensor_1", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "sensor_1",
        "rail",
        ["rail_id"],
        ["rail_id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("sensor_2_screw_id_fkey"), "sensor_2", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "sensor_2",
        "screw",
        ["screw_id"],
        ["screw_id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sensor_2", type_="foreignkey")
    op.create_foreign_key(
        op.f("sensor_2_screw_id_fkey"),
        "sensor_2",
        "screw",
        ["screw_id"],
        ["screw_id"],
    )
    op.drop_constraint(None, "sensor_1", type_="foreignkey")
    op.create_foreign_key(
        op.f("sensor_1_rail_id_fkey"),
        "sensor_1",
        "rail",
        ["rail_id"],
        ["rail_id"],
    )
    op.drop_constraint(None, "screw", type_="foreignkey")
    op.create_foreign_key(
        op.f("screw_rail_id_fkey"), "screw", "rail", ["rail_id"], ["rail_id"]
    )
    op.alter_column(
        "rail",
        "sleepers",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(length=255),
        postgresql_using="sleepers::text",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
