"""add side to rail

Revision ID: f0c129bdf9b3
Revises: c2d3399e842e
Create Date: 2025-12-20 22:05:53.829610

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f0c129bdf9b3"
down_revision: Union[str, Sequence[str], None] = "c2d3399e842e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rail",
        sa.Column(
            "side",
            sa.Enum(
                "LEFT", "RIGHT", "CENTER", name="rail_side", native_enum=False
            ),
            nullable=True,
            comment="Сторона рельса: левая/правая/центральная",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rail", "side")
    # ### end Alembic commands ###
