"""add table error

Revision ID: c2d3399e842e
Revises: 58116d414886
Create Date: 2025-12-09 21:21:33.899023

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c2d3399e842e"
down_revision: Union[str, Sequence[str], None] = "58116d414886"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "error",
        sa.Column(
            "error_id", sa.BigInteger(), autoincrement=True, nullable=False
        ),
        sa.Column(
            "rail_id",
            sa.BigInteger(),
            nullable=False,
            comment="идентификатор рельса",
        ),
        sa.Column(
            "screw_id",
            sa.BigInteger(),
            nullable=True,
            comment="идентификатор гайки",
        ),
        sa.Column("value_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("unit_of_measurement", sa.String(length=255), nullable=True),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("min_value", sa.Float(), nullable=False),
        sa.Column("max_value", sa.Float(), nullable=False),
        sa.Column(
            "is_critical",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "is_fixed",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["rail_id"],
            ["rail.rail_id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["screw_id"],
            ["screw.screw_id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("error_id"),
    )
    op.add_column(
        "threshold",
        sa.Column("unit_of_measurement", sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("threshold", "unit_of_measurement")
    op.drop_table("error")
    # ### end Alembic commands ###
