"""add rail and sensors

Revision ID: a8dad5e04156
Revises: 6ac740df9ddd
Create Date: 2025-11-24 20:13:17.299926

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a8dad5e04156"
down_revision: Union[str, Sequence[str], None] = "6ac740df9ddd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rail",
        sa.Column(
            "rail_id", sa.BigInteger(), autoincrement=True, nullable=False
        ),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=255), nullable=False),
        sa.Column("object_name", sa.String(length=255), nullable=True),
        sa.Column("fastening_type", sa.String(length=255), nullable=True),
        sa.Column("sleepers", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("rail_id"),
    )
    op.create_table(
        "sensor_1",
        sa.Column(
            "sensor1_id", sa.BigInteger(), autoincrement=True, nullable=False
        ),
        sa.Column(
            "encoder1",
            sa.BigInteger(),
            nullable=False,
            comment="значение энкодера 1",
        ),
        sa.Column(
            "encoder2",
            sa.BigInteger(),
            nullable=False,
            comment="значение энкодера 2",
        ),
        sa.Column(
            "encoder3",
            sa.BigInteger(),
            nullable=False,
            comment="значение энкодера 3",
        ),
        sa.Column(
            "encoder4",
            sa.BigInteger(),
            nullable=False,
            comment="значение энкодера 4",
        ),
        sa.Column(
            "mmAlongRail",
            sa.BigInteger(),
            nullable=False,
            comment="расстояние в мм от начала РШР",
        ),
        sa.Column(
            "laserOnRailLeft",
            sa.Boolean(),
            nullable=False,
            comment="лазерная полоса попадает на левый рельс (для забега)",
        ),
        sa.Column(
            "laserOnRailRight",
            sa.Boolean(),
            nullable=False,
            comment="лазерная полоса попадает на правый рельс (для забега)",
        ),
        sa.Column(
            "laserOnTieLeft",
            sa.Boolean(),
            nullable=False,
            comment="лазерная полоса попадает на шпалу слева (для эпюры)",
        ),
        sa.Column(
            "laserOnTieRight",
            sa.Boolean(),
            nullable=False,
            comment="лазерная полоса попадает на шпалу справа (для эпюры)",
        ),
        sa.Column(
            "mmGauge", sa.Float(), nullable=False, comment="ширина колеи в мм"
        ),
        sa.Column(
            "mmSideWearLeft",
            sa.Float(),
            nullable=False,
            comment="боковой износ левого рельса в мм",
        ),
        sa.Column(
            "mmSideWearRight",
            sa.Float(),
            nullable=False,
            comment="боковой износ правого рельса в мм",
        ),
        sa.Column(
            "mmVerticalWearLeft",
            sa.Float(),
            nullable=False,
            comment="вертикальный износ левого рельса в мм",
        ),
        sa.Column(
            "mmVerticalWearRight",
            sa.Float(),
            nullable=False,
            comment="вертикальный износ правого рельса в мм",
        ),
        sa.Column(
            "radRailTiltLeft",
            sa.Float(),
            nullable=False,
            comment="подуклонка левого рельса в рад",
        ),
        sa.Column(
            "radRailTiltRight",
            sa.Float(),
            nullable=False,
            comment="подуклонка правого рельса в рад",
        ),
        sa.Column(
            "mmBoltHeightLeftInner",
            sa.Float(),
            nullable=False,
            comment="высота внутреннего болта левого рельса в мм",
        ),
        sa.Column(
            "mmBoltHeightLeftOuter",
            sa.Float(),
            nullable=False,
            comment="высота внешнего болта левого рельса в мм",
        ),
        sa.Column(
            "mmBoltHeightRightInner",
            sa.Float(),
            nullable=False,
            comment="высота внутреннего болта правого рельса в мм",
        ),
        sa.Column(
            "mmBoltHeightRightOuter",
            sa.Float(),
            nullable=False,
            comment="высота внешнего болта правого рельса в мм",
        ),
        sa.Column(
            "timestamp",
            sa.DateTime(),
            nullable=False,
            comment="метка времени измерения",
        ),
        sa.Column(
            "rail_id",
            sa.BigInteger(),
            nullable=False,
            comment="идентификатор рельса",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["rail_id"],
            ["rail.rail_id"],
        ),
        sa.PrimaryKeyConstraint("sensor1_id"),
    )
    op.create_table(
        "sensor_2",
        sa.Column(
            "sensor2_id", sa.BigInteger(), autoincrement=True, nullable=False
        ),
        sa.Column(
            "resistance_1",
            sa.Float(),
            nullable=False,
            comment="Сопротивление 1",
        ),
        sa.Column(
            "resistance_2",
            sa.Float(),
            nullable=False,
            comment="Сопротивление 2 (<=4)",
        ),
        sa.Column(
            "moment_PC", sa.BigInteger(), nullable=False, comment="Момент ПЧ"
        ),
        sa.Column(
            "moment_percent",
            sa.BigInteger(),
            nullable=False,
            comment="Момент %",
        ),
        sa.Column(
            "moment_amperage_percent",
            sa.BigInteger(),
            nullable=False,
            comment="Момент (т) %",
        ),
        sa.Column(
            "turnover", sa.BigInteger(), nullable=False, comment="Обороты ПЧ"
        ),
        sa.Column(
            "amperage", sa.BigInteger(), nullable=False, comment="Ток ПЧ"
        ),
        sa.Column(
            "phase_amperage",
            sa.BigInteger(),
            nullable=False,
            comment="Фазный ток",
        ),
        sa.Column(
            "revolutions_PC_alt",
            sa.BigInteger(),
            nullable=False,
            comment="Обороты ПЧ alt",
        ),
        sa.Column(
            "status_PC", sa.BigInteger(), nullable=False, comment="Статус ПЧ"
        ),
        sa.Column(
            "timestamp",
            sa.DateTime(),
            nullable=False,
            comment="метка времени измерения",
        ),
        sa.Column(
            "rail_id",
            sa.BigInteger(),
            nullable=False,
            comment="идентификатор рельса",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["rail_id"],
            ["rail.rail_id"],
        ),
        sa.PrimaryKeyConstraint("sensor2_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sensor_2")
    op.drop_table("sensor_1")
    op.drop_table("rail")
    # ### end Alembic commands ###
