"""expand rail

Revision ID: 9e05f05be296
Revises: a8dad5e04156
Create Date: 2025-11-24 20:38:48.814341

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9e05f05be296"
down_revision: Union[str, Sequence[str], None] = "a8dad5e04156"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rail", sa.Column("start_time", sa.DateTime(), nullable=True)
    )
    op.add_column("rail", sa.Column("end_time", sa.DateTime(), nullable=True))
    op.add_column(
        "rail",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rail", "created_at")
    op.drop_column("rail", "end_time")
    op.drop_column("rail", "start_time")
    # ### end Alembic commands ###
