"""del status complete with errors

Revision ID: 58116d414886
Revises: b1370a9f7a34
Create Date: 2025-12-07 22:09:00.006685

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "58116d414886"
down_revision: Union[str, Sequence[str], None] = "b1370a9f7a34"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "screw",
        "status",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum(
            "IN_PROGRESS", "COMPLETED", name="screw_status", native_enum=False
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "screw",
        "status",
        existing_type=sa.Enum(
            "IN_PROGRESS", "COMPLETED", "COMPLETED_WITH_ERROR", name="screw_status", native_enum=False
        ),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
